version: '3'

services:
  db:
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'kohios'
      POSTGRES_PASSWORD: 'password'
    image: postgres:latest
    expose:
      - 5432

  web:
    restart: on-failure
    depends_on:
      - db
    environment:
      DATABASE_URL: 'postgres://postgres:password@db/kohios'
    build: .
    ports:
      - 8000:8000
    links:
      - db
